apiVersion: 1

datasources:
  - uid: JDS001  
    name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000