global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "rules/recording_rules.yml"

alerting:
  alertmanagers:
    - scheme: http
      timeout: 10s
      api_version: v1
      static_configs:
        - targets: []

# NOTES:
# 'metrics_path' defaults to '/metrics'.
# 'scheme' defaults to 'http'.

scrape_configs:

- job_name: prometheus  
  honor_timestamps: true
  static_configs:
    - targets:
      - localhost:9090

- job_name: cAdvisor
  static_configs:
    - targets:
      - cadvisor:8080

- job_name: node_exporter
  static_configs:
    - targets:
      - node_exporter:9100

- job_name: grafana
  static_configs:
    - targets:
      - grafana:3000

- job_name: proxy
  static_configs:
    - targets:
      - host.docker.internal:8000

- job_name: identity
  static_configs:
    - targets:
      - host.docker.internal:8001

- job_name: property
  static_configs:
    - targets:
      - host.docker.internal:8006

- job_name: reservation
  static_configs:
    - targets:
      - host.docker.internal:8011

- job_name: user
  static_configs:
    - targets:
      - host.docker.internal:8016
