global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - scheme: http
    timeout: 10s
    api_version: v1
    static_configs:
    - targets: []

scrape_configs:

# NOTES:
# metrics_path defaults to '/metrics'
# scheme defaults to 'http'.

- job_name: prometheus  
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics  
  scheme: http            
  static_configs:
  - targets:
    - localhost:9090

- job_name: cadvisor
  static_configs:
  - targets:
    - cadvisor:8080

- job_name: node_exporter
  static_configs:
  - targets:
    - node_exporter:9100

- job_name: identity
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - host.docker.internal:8001

- job_name: property
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - host.docker.internal:8006

- job_name: reservation
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - host.docker.internal:8011

- job_name: user
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - host.docker.internal:8016

- job_name: proxy
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - host.docker.internal:8000