#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0-preview AS base
USER app
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0-preview AS build
ARG BUILD_CONFIGURATION=Release
ENV ASPNETCORE_URLS=http://+:80
ENV ASPNETCORE_ENVIRONMENT=Docker
WORKDIR /src
COPY ["src/Shared/Shared.csproj", "Shared/"]
COPY ["src/Services/Identity/src/Identity/Identity.csproj", "Services/Identity/src/Identity/"]
COPY ["src/Services/Identity/src/Identity.API/Identity.API.csproj", "Services/Identity/src/Identity.API/"]
RUN --mount=type=cache,id=identity_nuget,target=/root/.nuget/packages \
    dotnet restore "Services/Identity/src/Identity.API/Identity.API.csproj"
COPY ["src/Shared", "Shared/"]
COPY ["src/Services/Identity/src/Identity/", "Services/Identity/src/Identity/"]
COPY ["src/Services/Identity/src/Identity.API/", "Services/Identity/src/Identity.API/"]
WORKDIR "/src/Services/Identity/src/Identity.API"
RUN --mount=type=cache,id=identity_nuget,target=/root/.nuget/packages \
    dotnet build "Identity.API.csproj" -c $BUILD_CONFIGURATION --no-restore

FROM build AS publish
RUN --mount=type=cache,id=identity_nuget,target=/root/.nuget/packages \
    dotnet publish "Identity.API.csproj" -c $BUILD_CONFIGURATION --no-build -o /app/publish /p:UseAppHost=false
RUN rm -rf /root/.nuget /root/.local /root/.nuget/packages/*

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Identity.API.dll"]