#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
ENV ASPNETCORE_URLS=http://+:80
ENV ASPNETCORE_ENVIRONMENT=Development

WORKDIR /src
COPY ["src/nuget.config", "."]
COPY ["src/Directory.Build.props", "."]
COPY ["src/Directory.Packages.props", "."]

COPY ["src/Shared/Directory.Build.props", "Shared/"]
COPY ["src/Shared/Shared.csproj", "Shared/"]
COPY ["src/Shared/packages.lock.json", "Shared/"]
COPY ["src/Services/User/Directory.Build.props", "Services/User/"]
COPY ["src/Services/User/src/User.Core/User.Core.csproj", "Services/User/src/User.Core/"]
COPY ["src/Services/User/src/User.Core/packages.lock.json", "Services/User/src/User.Core/"]
COPY ["src/Services/User/src/User.API/User.API.csproj", "Services/User/src/User.API/"]
COPY ["src/Services/User/src/User.API/packages.lock.json", "Services/User/src/User.API/"]
RUN --mount=type=cache,id=user_nuget,target=/root/.nuget/packages \
    dotnet restore "Services/User/src/User.API/User.API.csproj" --use-lock-file --locked-mode

COPY ["src/Shared/", "Shared/"]
COPY ["src/Services/User/src/User.Core/", "Services/User/src/User.Core/"]
COPY ["src/Services/User/src/User.API/", "Services/User/src/User.API/"]
RUN --mount=type=cache,id=user_nuget,target=/root/.nuget/packages \
    dotnet build "Services/User/src/User.API/User.API.csproj" -c $BUILD_CONFIGURATION --no-restore

FROM build AS publish
RUN --mount=type=cache,id=user_nuget,target=/root/.nuget/packages \
    dotnet publish "Services/User/src/User.API/User.API.csproj" -c $BUILD_CONFIGURATION --no-build -o /app/publish /p:UseAppHost=false
WORKDIR /
RUN rm -rf /root/.nuget /root/.local /root/.nuget/packages/*

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "User.API.dll"]