#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0-preview AS base
USER app
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0-preview AS build
ARG BUILD_CONFIGURATION=Release
ENV ASPNETCORE_URLS=http://+:80
ENV ASPNETCORE_ENVIRONMENT=Docker
WORKDIR /src
COPY ["src/Shared/Shared.csproj", "Shared/"]
COPY ["src/Services/Proxy/src/Proxy/Proxy.csproj", "Services/Proxy/src/Proxy/"]
COPY ["src/Services/Proxy/src/Proxy.API/Proxy.API.csproj", "Services/Proxy/src/Proxy.API/"]
RUN --mount=type=cache,id=proxy_nuget,target=/root/.nuget/packages \
	dotnet restore "Services/Proxy/src/Proxy.API/Proxy.API.csproj"
COPY ["src/Shared", "Shared/"]
COPY ["src/Services/Proxy/src/Proxy/", "Services/Proxy/src/Proxy/"]
COPY ["src/Services/Proxy/src/Proxy.API/", "Services/Proxy/src/Proxy.API/"]
WORKDIR "/src/Services/Proxy/src/Proxy.API"
RUN --mount=type=cache,id=proxy_nuget,target=/root/.nuget/packages \
	dotnet build "Proxy.API.csproj" -c $BUILD_CONFIGURATION --no-restore

FROM build AS publish
RUN --mount=type=cache,id=proxy_nuget,target=/root/.nuget/packages \
	dotnet publish "Proxy.API.csproj" -c $BUILD_CONFIGURATION --no-build -o /app/publish /p:UseAppHost=false
RUN rm -rf /root/.nuget /root/.local /root/.nuget/packages/*

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Proxy.API.dll"]