name: 'Pre-Release'
description: 'Bump patch version, create tag and GitHub pre-release, Build and publish Docker image (Pre-Release)'

inputs:
  image-name:
    description: 'Image name'
    required: true
  dockerfile-path:
    description: 'Dockerfile path'
    required: true
  registry-username:
    description: 'Container registry username'
    required: true
  registry-password:
    description: 'Container registry password'
    required: true
  gh-token:
    description: Github Personal Access Token
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set tag prefix
      id: set-tag-prefix
      if: ${{ github.ref == 'refs/heads/dev' }}
      shell: bash
      run: echo "::set-output name=tag_prefix::${{ inputs.image-name }}-v"

    - name: Bump version (patch) and create tag
      id: tag-step
      if: ${{ github.ref == 'refs/heads/dev' }}
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ inputs.gh-token }}
        append_to_pre_release_tag: 'dev'
        default_bump: patch
        tag_prefix: ${{ steps.set-tag-prefix.outputs.tag_prefix }}

    - name: Create a GitHub Pre-Release
      if: ${{ github.ref == 'refs/heads/dev' && success() }}
      uses: ncipollo/release-action@v1
      with:
        token: ${{ inputs.gh-token }}
        tag: ${{ steps.tag-step.outputs.new_tag }}
        name: Pre-Release ${{ steps.tag-step.outputs.new_tag }}
        body: ${{ steps.tag-step.outputs.changelog }}
        prerelease: true

    - name: Log in to Container Registry (Docker Hub)
      uses: docker/login-action@v2
      if: ${{ github.ref == 'refs/heads/dev' && success() }}
      with:
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-password }}

    - name: Build Docker image
      if: ${{ github.ref == 'refs/heads/dev' && success() }}
      shell: bash
      run: |
        docker build -t ${{ inputs.registry-username }}/${{ inputs.image-name }}:${{ steps.tag-step.outputs.new_tag }} -f "${{ github.workspace }}/${{ inputs.dockerfile-path }}" ${{ github.workspace }}/backend/

    - name: Push Docker image to Container Registry (Docker Hub)
      if: ${{ github.ref == 'refs/heads/dev' && success() }}
      shell: bash
      run: |
        docker push ${{ inputs.registry-username }}/${{ inputs.image-name }}:${{ steps.tag-step.outputs.new_tag }}
