version: "3.8"
name: "tourister"

services:

    postgres:
        image: postgres:15.4-alpine
        container_name: postgres
        restart: unless-stopped
        environment:
          - POSTGRES_USER=${POSTGRES_USER-}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-}
          - POSTGRES_EXTENSIONS=pg_trgm
        command:
          - "postgres"
          - "-c"
          - "wal_level=logical"
          - "-c"
          - "max_prepared_transactions=10"
        healthcheck:
          test: pg_isready -U postgres
        ports:
          - "5432:5432"
        volumes:
          - postgres:/var/lib/postgresql/data
        networks:
          - tourister-network

    mongo:
        image: mongo:7.0.5 
        container_name: mongo
        restart: unless-stopped
        command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
        healthcheck:
          test: echo "try { rs.status() } 
                catch (err) { 
                  rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) 
                }" | mongosh --port 27017 --quiet
        ports:
          - "27017:27017"
        networks:
          - tourister-network
        volumes:
          - mongo_data:/data/db
          - mongo_config:/data/configdb

    rabbitmq:
        image: rabbitmq:3.12.4-management
        container_name: rabbitmq
        restart: unless-stopped
        healthcheck:
          test: rabbitmq-diagnostics check_port_connectivity
        ports:
          - "5672:5672"
          - "15672:15672"
        networks:
          - tourister-network

    proxy:
        image: ${DOCKER_REGISTRY-}/proxy
        build:
          context: ../../
          dockerfile: src/Proxy/Dockerfile.prod
        container_name: proxy
        ports:
          - "8000:80"
        networks:
          - tourister-network

    identity:
        image: ${DOCKER_REGISTRY-}/identity
        build:
          context: ../../
          dockerfile: src/Services/Identity/Dockerfile.prod
        container_name: identity
        environment:
          - PG_CONNECTION=${IDENTITY_PG_CONNECTION}
          - RABBITMQ_CONNECTION=${RABBITMQ_CONNECTION}
        ports:
          - "8001:80"
        networks:
          - tourister-network
        depends_on: 
          postgres:
            condition: service_healthy
          rabbitmq:
            condition: service_healthy

    property:
        user: root                                          # TODO: Re-check and try removing "driver: local" from volume definition.
        image: ${DOCKER_REGISTRY-}/property
        build:
          context: ../../
          dockerfile: src/Services/Property/Dockerfile.prod
        container_name: property
        environment:
          - PG_CONNECTION=${PROPERTY_PG_CONNECTION}
          - RABBITMQ_CONNECTION=${RABBITMQ_CONNECTION}
        ports:
          - "8006:80"
        networks:
          - tourister-network
        volumes:
          - property_images:/app/wwwroot/property_images
        depends_on:
          postgres:
            condition: service_healthy
          rabbitmq:
            condition: service_healthy

    reservation:
        image: ${DOCKER_REGISTRY-}/reservation
        build:
          context: ../../
          dockerfile: src/Services/Reservation/Dockerfile.prod
        container_name: reservation
        environment:
          - MONGODB_CONNECTION=${RESERVATION_MONGODB_CONNECTION}
          - RABBITMQ_CONNECTION=${RABBITMQ_CONNECTION}
        ports:
          - "8011:80"
        networks:
          - tourister-network
        depends_on:
          mongo:
            condition: service_healthy
          rabbitmq:
            condition: service_healthy

    user:
        image: ${DOCKER_REGISTRY-}/user
        build:
          context: ../../
          dockerfile: src/Services/User/Dockerfile.prod
        container_name: user
        environment:
          - MONGODB_CONNECTION=${USER_MONGODB_CONNECTION}
          - RABBITMQ_CONNECTION=${RABBITMQ_CONNECTION}
          - RESERVATIONS_SERVICE_URL=http://reservation:80
        ports:
          - "8016:80"
        networks:
          - tourister-network
        depends_on:
          mongo:
            condition: service_healthy
          rabbitmq:
            condition: service_healthy

volumes:
  postgres:
  mongo_data:
  mongo_config:
  property_images:
    driver: local

networks:
    tourister-network:
